version: '3'
networks:
  realtime_simulation:
    driver: bridge
    name: ${NETWORK_NAME}

services:

  energyconsumption_simulation:
    build: ./energyconsumption_simulation
    depends_on:
      - kafka
      - hivemq
    networks:
      - ${NETWORK_NAME}

  mobility_simulation:
    build: ./mobility_simulation
    depends_on:
      - kafka
      - hivemq
    networks:
      - ${NETWORK_NAME}

  energyconsumption_bridge:
    build: ./energyconsumption_bridge
    depends_on:
      - kafka
      - hivemq
    networks:
      - ${NETWORK_NAME}

  mobility_bridge:
    build: ./mobility_bridge
    depends_on:
      - kafka
      - hivemq
    networks:
      - ${NETWORK_NAME}

  delivery_simulation:
    build: ./delivery_simulation
    depends_on:
      - kafka
      - hivemq
    networks:
      - ${NETWORK_NAME}

  delivery_bridge:
    build: ./delivery_bridge
    depends_on:
      - kafka
      - hivemq
    networks:
      - ${NETWORK_NAME}

  energyconsumption_consumer:
    build: ./energyconsumption_consumer
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    networks:
      - ${NETWORK_NAME}

  mqtt_to_db:
    build: ./mqtt_to_db
    depends_on:
      timescaledb:
        condition: service_healthy
      hivemq:
        condition: service_started
    environment:
      MQTT_BROKER: hivemq
      MQTT_PORT: "1883"
      MQTT_TOPICS: "node-red/#"
      DB_HOST: timescaledb
      DB_PORT: "5432"
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: yourdb
    networks:
      - ${NETWORK_NAME}

  delivery_webmap:
    build: ./delivery_webmap
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      DB_HOST: timescaledb
      DB_PORT: "5432"
      DB_USER: youruser
      DB_PASSWORD: yourpassword
      DB_NAME: yourdb
    ports:
      - "8081:80"
    networks:
      - ${NETWORK_NAME}

volumes:
  timescale_data:

